#############################################################################
# Makefile for building: hexengine
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Apr 9 00:51:51 2019
# Project:  hexengine.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile hexengine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/hexengine.cpp \
		src/config_form.cpp \
		src/ini_parser.cpp \
		src/forminjector.cpp \
		src/exceptions.cpp \
		src/common.cpp \
		src/disk.cpp \
		src/hexinjector.cpp moc_mainwindow.cpp \
		moc_hexengine.cpp \
		moc_config_form.cpp \
		moc_forminjector.cpp \
		moc_hexinjector.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		hexengine.o \
		config_form.o \
		ini_parser.o \
		forminjector.o \
		exceptions.o \
		common.o \
		disk.o \
		hexinjector.o \
		moc_mainwindow.o \
		moc_hexengine.o \
		moc_config_form.o \
		moc_forminjector.o \
		moc_hexinjector.o \
		qrc_resources.o
DIST          = android/AndroidManifest.xml \
		android/gradle/wrapper/gradle-wrapper.jar \
		android/gradlew \
		android/res/values/libs.xml \
		android/build.gradle \
		android/gradle/wrapper/gradle-wrapper.properties \
		android/gradlew.bat \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hexengine.pro
QMAKE_TARGET  = hexengine
DESTDIR       = 
TARGET        = hexengine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_config_form.h ui_forminjector.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: hexengine.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile hexengine.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile hexengine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hexengine1.0.0 || $(MKDIR) .tmp/hexengine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hexengine1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/hexengine.h src/config_form.h src/ini_parser.h src/forminjector.h src/exceptions.h src/common.h src/disk.h src/autorevision.h src/hexinjector.h .tmp/hexengine1.0.0/ && $(COPY_FILE) --parents res/resources.qrc .tmp/hexengine1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/hexengine.cpp src/config_form.cpp src/ini_parser.cpp src/forminjector.cpp src/exceptions.cpp src/common.cpp src/disk.cpp src/hexinjector.cpp .tmp/hexengine1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui ui/config_form.ui ui/forminjector.ui .tmp/hexengine1.0.0/ && (cd `dirname .tmp/hexengine1.0.0` && $(TAR) hexengine1.0.0.tar hexengine1.0.0 && $(COMPRESS) hexengine1.0.0.tar) && $(MOVE) `dirname .tmp/hexengine1.0.0`/hexengine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hexengine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_hexengine.cpp moc_config_form.cpp moc_forminjector.cpp moc_hexinjector.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_hexengine.cpp moc_config_form.cpp moc_forminjector.cpp moc_hexinjector.cpp
moc_mainwindow.cpp: src/hexengine.h \
		src/mainwindow.h \
		src/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

moc_hexengine.cpp: src/mainwindow.h \
		src/hexengine.h \
		src/hexengine.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/hexengine.h -o moc_hexengine.cpp

moc_config_form.cpp: src/config_form.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/config_form.h -o moc_config_form.cpp

moc_forminjector.cpp: src/forminjector.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/forminjector.h -o moc_forminjector.cpp

moc_hexinjector.cpp: src/hexengine.h \
		src/mainwindow.h \
		src/hexinjector.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/hexinjector.h -o moc_hexinjector.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: res/resources.qrc
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name resources res/resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_config_form.h ui_forminjector.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_config_form.h ui_forminjector.h
ui_mainwindow.h: ui/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

ui_config_form.h: ui/config_form.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/config_form.ui -o ui_config_form.h

ui_forminjector.h: ui/forminjector.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/forminjector.ui -o ui_forminjector.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/hexengine.h \
		src/autorevision.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/hexengine.h \
		ui_mainwindow.h \
		src/config_form.h \
		src/forminjector.h \
		src/exceptions.h \
		src/common.h \
		src/autorevision.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

hexengine.o: src/hexengine.cpp src/hexengine.h \
		src/mainwindow.h \
		src/ini_parser.h \
		src/exceptions.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hexengine.o src/hexengine.cpp

config_form.o: src/config_form.cpp src/config_form.h \
		ui_config_form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config_form.o src/config_form.cpp

ini_parser.o: src/ini_parser.cpp src/ini_parser.h \
		src/config_form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ini_parser.o src/ini_parser.cpp

forminjector.o: src/forminjector.cpp src/forminjector.h \
		ui_forminjector.h \
		src/hexengine.h \
		src/mainwindow.h \
		src/common.h \
		src/exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forminjector.o src/forminjector.cpp

exceptions.o: src/exceptions.cpp src/exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exceptions.o src/exceptions.cpp

common.o: src/common.cpp src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o src/common.cpp

disk.o: src/disk.cpp src/disk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o disk.o src/disk.cpp

hexinjector.o: src/hexinjector.cpp src/hexinjector.h \
		src/hexengine.h \
		src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hexinjector.o src/hexinjector.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_hexengine.o: moc_hexengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hexengine.o moc_hexengine.cpp

moc_config_form.o: moc_config_form.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config_form.o moc_config_form.cpp

moc_forminjector.o: moc_forminjector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_forminjector.o moc_forminjector.cpp

moc_hexinjector.o: moc_hexinjector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hexinjector.o moc_hexinjector.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

